sanic 21.3 support
sanic-org/sanic-openapi pull request #218
Opened 2021-03-26 14:35 UTC by artcg

2021-04-15 13:46 UTC, jonragnarsson commented
I need this.

2021-05-04 18:29 UTC, ahopkins requested changes

2021-05-04 18:29 UTC, ahopkins commented on sanic_openapi/utils.py
> +                for method_handlers in route.handlers.values():
I think I broke this part on you.... :grimacing: 

You should not need to do all this crazy nested looking to get the handler:

```
yield blueprint.name, route.handler
```

2021-05-04 18:47 UTC, ahopkins commented on sanic_openapi/utils.py
> +                for method_handlers in route.handlers.values():
FYI - I am building the patch for this and will push it.

2021-05-04 20:59 UTC, ahopkins submitted a review, later dismissed

2021-05-04 21:07 UTC, ahopkins approved these changes

2021-05-04 21:08 UTC, merged